project_id = "lbyticixgkicsfvoekhn"

[functions.hello-world]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.upload-dataset]
verify_jwt = true

[functions.get-dataset]
verify_jwt = true

[functions.generate-overview]
verify_jwt = true

[functions.preprocess-dataset]
verify_jwt = true

[functions.preview-preprocessing]
verify_jwt = true

